spring:
  application:
    name: foodie
  datasource:
    url: ${DATABASE_URL:jdbc:h2:file:./data/foodie-db;DB_CLOSE_ON_EXIT=FALSE}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
    username: ${DATABASE_USER:sa}
    password: ${DATABASE_PASSWORD:}
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2-console
  jpa:
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:444075693846-lsrjv7upe9d37fmesmd668g5u0l81hl4.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
            scope: openid, profile, email

server:
  port: ${PORT:9090}
  address: ${SERVER_ADDRESS:0.0.0.0}
  forward-headers-strategy: framework

spring.servlet.multipart:
  max-file-size: 20MB
  max-request-size: 20MB

# Proxy config for external API calls (Open Food Facts)
app:
  cloudflare:
    account-id: ${CLOUDFLARE_ACCOUNT_ID:507ac87d769dd2286a403c698af771b3}
    api-token: ${CLOUDFLARE_API_TOKEN:cfut_mXSke9LAlqWziygC0wlSRsaKEO1gV2qcwCRkFhua49697c42}
  proxy:
    host: ${PROXY_HOST:}
    port: ${PROXY_PORT:0}

